package com.barter.model;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.id
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.parentid
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    private String parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.name
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.type
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.img
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.id
     *
     * @return the value of t_category.id
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.id
     *
     * @param id the value for t_category.id
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.parentid
     *
     * @return the value of t_category.parentid
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.parentid
     *
     * @param parentid the value for t_category.parentid
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.name
     *
     * @return the value of t_category.name
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.name
     *
     * @param name the value for t_category.name
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.type
     *
     * @return the value of t_category.type
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.type
     *
     * @param type the value for t_category.type
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.img
     *
     * @return the value of t_category.img
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.img
     *
     * @param img the value for t_category.img
     *
     * @mbg.generated Thu Nov 14 15:33:41 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}